package com.infy.exceptions;

public class ExDEmo2 {

	public static void main(String[] args) {
	
		
		int a=10/2;
		int b[]= {3,2,4};
		try {
			  //db
			//socket
			//file
		
		}
		
		catch(ArithmeticException e) {
			
			System.out.println(e);
		}
		
		
		
	
		
		
		
	}

}
